apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aggressive-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.global-static-ip-name: peddecord-photo-static-ip
spec:
  tls:
    - hosts:
        - api.peddecord.photo
      secretName: api-peddecord-photo-tls
    - hosts:
        - www.peddecord.photo
      secretName: peddecord-photo-tls
  rules:
    - host: www.peddecord.photo
      http:
        paths:
          - backend:
              serviceName: node-app-np
              servicePort: 3000
    - host: api.peddecord.photo
      http:
        paths:
          - backend:
              serviceName: api-v1-np
              servicePort: 3000
    - host: peddecord.photo
      http:
        paths:
          - backend:
              serviceName: node-app-np
              servicePort: 3000
